### ISSUE TITLE
Electrs is not compatible with Embassy backups

### ISSUE THREAD

**Issue by SeaSquared24** [chrisguida/electrs-wrapper#3]
I got my shared folder set up and initiated a backup. electrs was fourth on the list and has been spinning for at least 30 min. 
![image](https://user-images.githubusercontent.com/84783719/160256950-5aa14c79-6b39-42c1-b7b0-aacee97861bd.png)

**Comment by chrisguida** [comment]
Right, I haven't implemented backups yet.  Still to do:

Fix proxy autoconfig rules
Fix health check
Fix backups
Fix readme
Fix instructions
Do something about memory usage

**Comment by chrisguida** [comment]
backups work as of 0572772c6e4a210ed5db9f5552fb4ac6b109dc4e
