### ISSUE TITLE
Electrs Crash Report

### ISSUE THREAD

**Issue by SeaSquared24** [chrisguida/electrs-wrapper#6]
Not really sure what caused this. I was having issues logging into Embassy. At first logged in, Embassy UI seemed frozen. Shut down firefox and cleared cache, reattempted logging in, never made it in, just spinning. Hard reset by unplugging power got me in. ElectRS crash in notifications. Not sure if the crash report at the end is saying that the Embassy was frozen or not. Bitcoin Daemon unavailable...

```The service electrs has crashed with the following exit code: 1 Details: Starting electrs 0.9.5 on aarch64 linux with Config { network: Bitcoin, db_path: "./db/bitcoin", daemon_dir: "/root/.bitcoin", daemon_auth: UserPass("bitcoin", ""), daemon_rpc_addr: 172.18.0.5:8332, daemon_p2p_addr: 172.18.0.5:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.5 (Electrum Rust Server)!", args: [] } [2022-04-14T13:21:06.670Z INFO electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224 [2022-04-14T13:21:06.670Z INFO electrs::server] serving Electrum RPC on 0.0.0.0:50001 [2022-04-14T13:21:07.142Z INFO electrs::db] "./db/bitcoin": 142 SST files, 34.736926679 GB, 4.323709353 Grows [2022-04-14T13:21:12.534Z INFO electrs::chain] loading 731839 headers, tip=000000000000000000076cce2ac5551e08dd62f538104a3171017a6dca32b2f6 [2022-04-14T13:21:16.612Z INFO electrs::chain] chain updated: tip=000000000000000000076cce2ac5551e08dd62f538104a3171017a6dca32b2f6, height=731839 [2022-04-14T13:21:16.694Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:17.698Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:18.701Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:19.703Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:20.705Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:21.707Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:22.709Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:23.711Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:24.714Z INFO electrs::daemon] waiting for RPC warmup: Loading block index... [2022-04-14T13:21:25.716Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:26.718Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:27.720Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:28.723Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:29.725Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:30.728Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:31.730Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:32.732Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:33.735Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:34.737Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:35.739Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:36.741Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:37.743Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:38.745Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:39.747Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:40.749Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:41.751Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:42.754Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:43.757Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:44.759Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:45.761Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:46.763Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:47.765Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:48.767Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:49.768Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:50.770Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:51.772Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:52.775Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:53.777Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:54.779Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:55.782Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:56.784Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:57.787Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:58.789Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:21:59.792Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:22:00.794Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:22:01.796Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:22:02.798Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:22:03.800Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:22:04.802Z INFO electrs::daemon] waiting for RPC warmup: Verifying blocks... [2022-04-14T13:22:05.806Z INFO electrs::daemon] waiting for RPC warmup: Loading P2P addresses... [2022-04-14T13:22:13.273Z INFO electrs::daemon] waiting for 62 blocks to download (IBD) [2022-04-14T13:22:33.797Z INFO electrs::db] closing DB at ./db/bitcoin Error: electrs failed Caused by: 0: bitcoind RPC polling failed 1: daemon not available 2: JSON-RPC error: transport error: Didn't receive response data in time, timed out. ```

**Comment by chrisguida** [comment]
Looks like your node was catching up the last 62 blocks of the chain. Electrs exits when bitcoin hasn't caught up to the tip of the chain yet. Do you have the latest version of electrs on beta? I actually added a health check to check to see if bitcoin is synced, but it's not yet working due to this OS bug: https://github.com/Start9Labs/embassy-os/issues/1383

The latest version of electrs has a dependency error that won't go away until this bug is fixed. Can you verify that this dependency error is there for you?

**Comment by SeaSquared24** [comment]
I don't think I was on the latest. Just reinstalled. All I know on the prior version is that when ElectRS exits, it shuts the whole box down.

Ok I see that the Health Check is on the latest version. I'm now waiting for index. I did not add a .toml file but it seems to be working. Did I store that in a persistent location or is that config now included in the install?
***edit: I actually reinstalled the 0.9.5 version. I am in the Alpha Marketplace. I don't see a 0.9.6 which is what is in your screenshots on the OS bug link

**Comment by chrisguida** [comment]
Oh, use beta. I used 0.9.6 on alpha to practice yanking packages :p

**Comment by SeaSquared24** [comment]
Link to that? Not finding on the Start9 site

**Comment by chrisguida** [comment]
dm me on matrix
